const errorMsg = {
    USER_NOT_FOUND: 'User Not Found',
    USER_ALREADY_EXIST: 'User Already Exist',
    RECORD_NOT_FOUND_TO_DELETE: 'Record Not Found To Delete',
    RECORD_NOT_FOUND_TO_UPDATE: 'Record Not Found To Update',
    LOGIN_FAILED: 'Failed To Login',
    FAILED_TO_CREATE_MAIN_GROUP: 'Failed To Create Main Activity',
    GROUP_ALREADY_EXIST: 'Group Already Exist',
    GROUP_NOT_FOUND: 'Main Group Not Found',
    FAILED_TO_DELETE_MAIN_GROUP: 'Failed To Delete Main Activity',
    FAILED_TO_CREATE_SUB_ACTIVITY: 'Failed To Create Sub Activity',
    SUB_ACTIVITY_NOT_FOUND: 'Sub Activity Not Found',
    SUB_ACTIVITY_ALREADY_EXIST: 'Sub Activity Already Exist',
    FAILED_TO_CREATE_CHECK_LIST: 'Failed To Create Check List',
    CHECK_LIST_NOT_FOUND: 'Check List Not Found',
    INCORRECT_PASSWORD: 'Incorrect Password',
    USER_TYPE_ALREADY_EXIST: 'User Type Already Exist',
    ROLE_ALREADY_EXIST: 'Role Type Already Exist',
    PLEASE_CHECKIN_BEFORE_UPDATING_LOGOUT_TIME: 'Please Checkin Before Updating Logout Time',
    CHECK_USER_MOBILE_NUMBER_AND_ATT_DATE: 'Check User Mobile Number and Attendance Date',
    FAILED_TO_CREATE_MAIN_LOCATION: 'Failed To Create Main Location',
    FAILED_TO_CREATE_SUB_LOCATION: 'Failed To Create Sub Location',
    FILTER_TYPE_ALREADY_EXIST: 'Filter Type Already Exist',
    REPORT_NOT_FOUND: 'Report Not Found',
    MOBILE_NUMBER_ALREADY_EXIST: 'Mobile Number Already Exist',
    USER_NAME_ALREADY_EXIST: 'User Name Already Exist',
    EMAIL_ALREADY_EXIST: 'Email Already Exist',
    UNAUTHORIZED_USER: 'UnAuthorized User'
};

const successMsg = {
    ADMIN_CREATED_SUCCESSFULLY: 'Admin Created SuccessFully',
    RECORD_DELETED_SUCCESSFULLY: 'Record Deleted Successfully',
    RECORD_UPDATED_SUCCESSFULLY: 'Record Updated Successfully',
    ADMIN_LOGGEDIN_SUCCESSFULLY: 'Admin Logged In Successfully',
    ADMIN_LOGGEDOUT_SUCCESSFULLY: 'Admin Logged Out Successfully',
    USER_CREATED_SUCCESSFULLY: 'User Created SuccessFully',
    DATA_RETRIVED_SUCCESSFULLY: 'Data Retrived Successfully',
    USER_LOGGEDIN_SUCCESSFULLY: 'User Login Success',
    GROUP_CREATED_SUCCESSFULLY: 'Main Activity Created Successfully',
    GROUP_LIST_VIEWED_SUCCESSFULLY: 'Activity List Viewed Successfully',
    GROUP_DELETED_SUCCESSFULLY: 'Activity Removed Successfully',
    GROUP_UPDATED_SUCCESSFULLY: 'Activity Updated Successfully',
    SUB_ACTIVITY_CREATED_SUCCESSFULLY: 'Sub Activity Created Successfully',
    SUB_ACTIVITY_LIST_VIEWED_SUCCESSFULLY: 'Sub Activity List Viewed Successfully',
    CHECK_LIST_CREATED_SUCCESSFULLY: 'Check List Created Successfully',
    CHECK_LIST_SUBMITTED_SUCCESSFULLY: 'Check List Submitted Successfully',
    USER_TYPE_CREATED_SUCCESSFULLY: 'User Type Created Successfully',
    ROLE_CREATED_SUCCESSFULLY: 'Role Created Successfully',
    USER_CHECKEDIN_SUCCESSFULLY: 'User Checked In Successfully',
    JOB_MANAGEMENT_CREATED_SUCCESSFULLY: 'Job Created Successfully',
    MAIN_LOCATION_CREATED_SUCCESSFULLY: 'Main Location Created Successfully',
    SUB_LOCATION_CREATED_SUCCESSFULLY: 'Sub Location Created Successfully',
    LOGIN_STATUS_RETRIVED: 'Login Status Retrived',
    LOGGED_OUT_SUCCESSFULLY: 'Logged Out Successfully ',
    TICKET_RAISED_SUCCESSFULLY: 'Ticket Raised Successfully',
    FILE_UPLOAD_SUCCESS: 'Successfully Uploaded File',
    REPORTS_VIEWED_SUCCESSFULLY: 'Reports Viewed Successfully',
    SPARE_CREATED_SUCCESSFULLY: 'Spare Created Successfully',
    FORM_SUBMITTED_SUCCESSFULLY: 'Form Submitted Successfully',
    ACTIVITY_CREATED_SUCCESSFULLY: 'Activity Created Successfully'
};

module.exports = { errorMsg, successMsg };
